version: "3.8"
services:
  n8n:
   image: n8nio/n8n:latest
   container_name: n8n
   restart: always
   ports:
     - "127.0.0.1:5678:5678"
   environment:
    - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
    - N8N_PORT=5678
    - N8N_PROTOCOL=https
    - NODE_ENV=production
    - WWEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
    - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
   volumes:
    - n8n_data:/home/node/.n8n
